apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: grafana-operatorgroup
  namespace: grafana-operator
spec:
  targetNamespaces:
  - grafana-operator
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: my-grafana-operator
  namespace: grafana-operator
spec:
  channel: v4
  name: grafana-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
