apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "multitenancy.example.net/v1alpha1",
          "kind": "TenancyFrontend",
          "metadata": {
            "name": "tenancyfrontendsample"
          },
          "spec": {
            "displayname": "MyFrontendDisplayname",
            "size": 1
          }
        },
        {
          "apiVersion": "multitenancy.example.net/v2alpha2",
          "kind": "TenancyFrontend",
          "metadata": {
            "name": "tenancyfrontend-sample"
          },
          "spec": {
            "catalogname": "Movies",
            "displayname": "Movie-Store",
            "size": 1
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.17.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: frontendoperator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TenancyFrontend is the Schema for the tenancyfrontends API
      displayName: Tenancy Frontend
      kind: TenancyFrontend
      name: tenancyfrontends.multitenancy.example.net
      version: v1alpha1
    - description: TenancyFrontend is the Schema for the tenancyfrontends API
      displayName: Tenancy Frontend
      kind: TenancyFrontend
      name: tenancyfrontends.multitenancy.example.net
      version: v2alpha2
  description: This is an example operator to deploy a simple web application
  displayName: FrontendOperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - multitenancy.example.net
          resources:
          - tenancyfrontends
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - multitenancy.example.net
          resources:
          - tenancyfrontends/finalizers
          verbs:
          - update
        - apiGroups:
          - multitenancy.example.net
          resources:
          - tenancyfrontends/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: frontendoperator-controller-manager
      deployments:
      - name: frontendoperator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/tsuedbroecker/frontendcontroller:v4
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: frontendoperator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: frontendoperator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - example
  - go
  - webapplication
  - ngnix
  links:
  - name: Frontendoperator
    url: https://frontendoperator.domain
  maturity: alpha
  provider:
    name: Thomas Suedbroecker
  version: 0.0.2
