apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: frontendoperator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: TenancyFrontend is the Schema for the tenancyfrontends API
      displayName: Tenancy Frontend
      kind: TenancyFrontend
      name: tenancyfrontends.multitenancy.example.net
      version: v2alpha2
    - description: TenancyFrontend is the Schema for the tenancyfrontends API
      displayName: Tenancy Frontend
      kind: TenancyFrontend
      name: tenancyfrontends.multitenancy.example.net
      version: v1alpha1
  description: This is an example operator to deploy a simple web application
  displayName: FrontendOperator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - example
  - go
  - webapplication
  - ngnix
  links:
  - name: Frontendoperator
    url: https://frontendoperator.domain
  maturity: alpha
  provider:
    name: Thomas Suedbroecker
  version: 0.0.0
