# permissions for end users to view tenancyfrontends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tenancyfrontend-viewer-role
rules:
- apiGroups:
  - multitenancy.example.net
  resources:
  - tenancyfrontends
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenancy.example.net
  resources:
  - tenancyfrontends/status
  verbs:
  - get
